sudo: required
services:
  - docker

before_install:
  - docker build -t jjpieters/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true jjpieters/react-app npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "react-app"
  env: "ReactApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-645791015626"
  bucket_path: "react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
